import React from 'react';

function HistoryResult({ values }) {
  return (
    <div>
      <h1>{values.bedNumber}</h1>

      <p>
        NOTA: PACIENTE VALORADO CON TODAS LAS MEDIDAS DE PROTECCION REQUERIDAS POR EVENTUALIDAD DE
        PANDEMIA POR VIRUS SARS COV 2 EVOLUCION MÉDICA CUIDADOS BASICOS/INTERMEDIOS NEONATALES
      </p>

      <p>
        NEONATO EN SUS PRIMERAS HORAS DE VIDA Y ESTANCIA HOSPITALARIA CON DIAGNÓSTICOS DE: -RECIEN
        NACIDO PRETERMINO MASCULINO/FEMENINO DE XX SEMANAS POR BALLARD EGC XX -PESO Y TALLA
        ADECUADOS PARA SU EDAD GESTACIONAL
      </p>

      <h2>BALANCE HIDIRICO 12HR</h2>
      <p>PESO XXXX GR GLUCOMETRIA 83 MG DL LA XXX CC LE XXX CC GU: XXX CC/KG/HORA</p>

      <h2> EXAMEN FISICO </h2>
      <p>SIGNOS VITALES FC: 100 LPM – FR: 35RPM – SAT02: 99% T 36.5°C </p>

      <p>
        NORMOCEFALO, FONTANELA ANTERIOR NORMOTENSA, POSTERIOR PUNTIFORME, PUPILAS ISOCORICAS
        NORMOREACTIVAS, ESCLERAS ANICTERICAS, NARINAS PERMEABLES, MUCOSA ORAL HUMEDA, SOG CERRADA,
        CUELLO MOVIL SIN ADENOPATIAS PALPABLES.
      </p>

      <p>
        TÓRAX SIMETRICO, EXPANSIBLE, SIN TIRAJES, NO AGREGADOS. RUIDOS CARDIACOS RITMICOS SIN
        SOPLOS.
      </p>

      <p>
        ABDOMEN BLANDO, DEPRESIBLE, NO IMPRESIONA DOLOR A LA PALPACION, NO MASAS NO MEGALIAS, ONFALO
        CLAMPEADO SIN INFECCIONES
      </p>

      <p> GENITOURINARIO NORMOCONFIGURADO PARA SEXO Y EDAD.</p>

      <p>
        EXTREMIDADES EUTROFICAS, SIN EDEMAS, LLENADO CAPILAR{'<'}2 SG, PULSOS DISTALES PRESENTES Y
        SIMETRICOS.
      </p>

      <p>
        NEUROLÓGICO, ACTIVO, REACTIVO CON RESPUESTA A ESTIMULOS, REFLEJOS PRIMITIVOS PRESENTES,
        LIBRE DE CRISIS NEONATALES.
      </p>

      <p> PIEL Y ANEXOS ÍNTEGRA, SIN LESIONES, ROSADA</p>

      <h2> REPORTE DE PARACLÍNICOS</h2>
      <p>XX/12/21 CH PCR GLICEMIA CA GASES</p>

      <h2>ANALISIS </h2>
      <p>PACIENTE PRETERMINO EN REGULARES CONDICIONES GENERALES. CON IDX PREVIAMENTE DESCRITOS. </p>

      <p> NEUROLOGICO: ACTIVO REACTIVO, SIN DEFICIT APARENTE, NI CRISIS. </p>

      <p>RESPIRATORIO: TOLERANDO OXÍGENO AMBIENTE. PATRON RESPIRATORIO ADECUADO, NORMOSATURADO.</p>

      <p>
        HEMODINAMICO: MANTIENE SIGNOS VITALES ESTABLES NO SOPORTES, BIEN PERFUNDIDO, NO GRADIENTE
        TERMICO.
      </p>

      <p>GI: TOLERANDO APORTE ENTERAL POR SONDA, HIDRATADO, NORMOGLICEMICO,</p>

      <p> RENAL: DIURESIS POR PAÑAL PRESENTE, NO EDEMAS.</p>

      <p> INFECCIOSO: NO DISTERMIAS.</p>

      <p>
        SE INDICA TOMA DE PARACLINICOS Y ESTUDIOS COMPLEMENTARIOS. SE EXPLICA A LOS PADRES QUIENES
        REFIEREN ENTENDER Y ACEPTAR, PRONOSTICO SUJETO A EVOLUCION
      </p>

      <h2> PLAN:</h2>
      <p>1. ESTANCIA -CUIDADOS INTERMEDIOS NEONATALES </p>

      <p> 2. DIETA </p>

      <p> 3. OXÍGENO -NINGUNO </p>

      <p>4. FARMACOLÓGICO</p>
      <p>5. CUIDADOS DE ENFERMERÍA </p>
      <ul>
        <li>CUIDADOS BASICOS NEONATALES</li>
        <li>MONITORIZACIÓN ELECTRONICA NO INVASIVA</li>
        <li>GLUCOMETRIA CADA 12 HORAS</li>
        <li>CUIDADOS DE ENFERMERÍA</li>
        <li>PESO DIARIO -CONTROL DE LA, LE, BH</li>
        <li>CONTROL DE SIGNOS VITALES Y AVISAR CAMBIOS</li>
      </ul>

      <p> 6. PARACLÍNICOS SOLICITADOS </p>

      <p>7. IMÁGENES DIAGNÓSTICAS SOLICITADAS -</p>

      <p> 8. ASISTENCIAL </p>

      <p> 9. PENDIENTE -</p>
    </div>
  );
}

export default HistoryResult;
